version: '3.6'

services:
  db:
    image: mariadb:10.8@sha256:49e30bbd13b7341ef83c7f3b09cc2191d2a02667d77ae9d6421c7e86133b8633
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      wp:
        ipv4_address: 172.25.0.3

  wordpress:
    image: wordpress:apache@sha256:c160b3abeb958081c47e27166fa613d3116e209b3d2736365b01b777bd95b1bb
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      wp:
        ipv4_address: 172.25.0.2
    volumes:
      - .:/var/www/html/wp-content/plugins/ww-yubico-otp

volumes:
  db:

networks:
  wp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
