name: Release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Generate self-contained package
        run: |
          git archive --format=tar --prefix=ww-yubico-otp/ HEAD | (cd /var/tmp/ && tar xf -)
          cp composer.lock /var/tmp/ww-yubico-otp/
          (cd /var/tmp/ww-yubico-otp && composer install --no-dev --no-interaction)
          (cd /var/tmp && zip -r -9 ww-yubico-otp.zip ww-yubico-otp)

      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # renovate: tag=v0.1.14
        with:
          generate_release_notes: true
          files: |
            /var/tmp/ww-yubico-otp.zip
