name: Static Code Analysis

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Analyze the code with Psalm
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Check out source code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Set up PHP
        uses: shivammathur/setup-php@1a18b2267f80291a81ca1d33e7c851fe09e7dfc4 # tag=2.22.0
        with:
          coverage: none

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@7f9021e5513f650c97a067ad64e907e23fd8276e # tag=2.1.1

      - name: Run psalm
        run: composer psalm -- --output-format=github
