name: Static Code Analysis

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Analyze the code with Psalm
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Check out source code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

      - name: Set up PHP
        uses: shivammathur/setup-php@448bd61c6fe9db2113173467e4c22b87ddc2971a # tag=v2
        with:
          coverage: none

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6 # renovate: tag=2.1.0

      - name: Run psalm
        run: composer psalm -- --output-format=github
